project:
  title: "Bayesian data analysis"
  type: website
website:
  sidebar:
    style: "docked"
    contents: /*
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
author: "Aki Vehtari et al."
format: 
  html:
    toc: true
    code-tools: true
    code-line-numbers: true
    standalone: true
    self-contained: true
    embed-resources: true  
    number-sections: true
    mainfont: Georgia, serif
    fontsize: 1.2em
reference-location: margin
citation-location: margin 
comments:
  hypothesis: true
editor: source
execute:
  freeze: auto
  cache: true
  daemon: 999999 